### PR TITLE
Update to bevy 0.13

### PR DESCRIPTION
**Pull request by JasmineLowen**
Most of the changes are documented in the commits. The commits are all independent and can be reviewed in sequence (except for https://github.com/kulkalkul/bevy_mod_billboard/pull/22/commits/2df3c5a3de0a3460cfa5a7ceff5844621f264dc3 which is superseded by https://github.com/kulkalkul/bevy_mod_billboard/pull/22/commits/04b033f44b3f4a2aea032c0b414d3878f400232b, so you can skip the former)

Please pay special attention to https://github.com/kulkalkul/bevy_mod_billboard/pull/22/commits/04b033f44b3f4a2aea032c0b414d3878f400232b while reviewing.

### CODE REVIEW

**Comment by kulkalkul** [comment]
Thanks a lot!

I'm basing this off bevy_sprite, so:
- https://github.com/kulkalkul/bevy_mod_billboard/pull/22/commits/552e37d413e67c72b85e1e927832970ab6640d32
``AssetsEvent::Unused`` isn't used for removal here, so I removed that.
Ref: https://github.com/bevyengine/bevy/blob/v0.13.0/crates/bevy_sprite/src/render/mod.rs#L571

- https://github.com/kulkalkul/bevy_mod_billboard/pull/22/commits/91be8e9a631853c503c1cf0a22703d753ba74a0a
Changed ``expect``s into ``RenderCommandResult::Failure`` returns as that seems like what bevy prefers.

``GlyphAtlasInfo.texture`` is added with new 0.13 changes and seems to be the correct texture for the glyph, so I removed the part that groups glyphs based on textures and used that for grouping instead (it was also similar before where each texture was its own batch). Though, both versions have performance regressions with text compared to 0.5 version of the crate. Though I don't think the issue is with the text recomputation because the static case is also regressed. So, either render pipeline is doing something wrong or bevy's font stuff has some extra work to do.
Ref: https://github.com/bevyengine/bevy/pull/5103/files#diff-3cdcf2872f0b28723cc502cd8deaea811e9e92fba77d02bf8c1d75eee93fa9c3R47

| Mode            | Static | Recomputed |
| -----------      | ------ | -------------- |
| Text(old)        | 109       | 13              |
| Text(new)        | 71.5  | 10.6              |

Can you check the changes I made to the PR? I am okay with the regression because it is still way better compared to the previous version of the crate.

**Review by JasmineLowen — COMMENTED** [review]
I can't approve since it's my own PR xD

It looks good though, thanks for the thorough review and for immediately fixing things yourself <3

LGTM

**Comment by kulkalkul** [comment]
Oups, accidentally clicked on revert 🤦
Before publishing it, I'll look at what's causing the performance regression and see if it is an easy fix. So it might take several days for crate release. Would that be a problem?

**Comment by JasmineLowen** [comment]
> Oups, accidentally clicked on revert 🤦 Before publishing it, I'll look at what's causing the performance regression and see if it is an easy fix. So it might take several days for crate release. Would that be a problem?

Nope, that's fine. I'm just pointing to your github repo in the meantime directly 👍🏼

**Comment by dividebysandwich** [comment]
Thanks a lot for the upgrade PR btw! Much appreciated.

**Comment by marcelchampagne** [comment]
Happy to see 0.13 support is here! @kulkalkul, any update on the crate release? Thanks!

**Comment by kulkalkul** [comment]
> Happy to see 0.13 support is here! @kulkalkul, any update on the crate release? Thanks!

Haven't checked it yet, I'll do soon enough

**Pull request merged**
