### PR TITLE
migrate to bevy 0.11

### LINKED ISSUE #12: Upgrade to Bevy 0.11

### PR DESCRIPTION
**Pull request by robtfm**
the changes are quite straightforward

### CODE REVIEW

**Comment by kulkalkul** [comment]
Thanks a lot! I want to check how mesh pipeline works in 0.11 to see if I can upgrade anything. Then I can merge and release it if that's okay to you. It should take around 2-3 days at max 😅

**Comment by robtfm** [comment]
Perfect, don’t rush on my account

**Comment by robtfm** [comment]
i have some small changes to allow use with hdr (+7/-2), would you like me to add them to this pr or make a separate one?

```diff
--- a/src/pipeline.rs
+++ b/src/pipeline.rs
@@ -2,7 +2,7 @@ use crate::{
     BillboardDepth, BillboardLockAxis, ATTRIBUTE_TEXTURE_ARRAY_INDEX, BILLBOARD_SHADER_HANDLE,
 };
 
-use bevy::ecs::query::ROQueryItem;
+use bevy::{ecs::query::ROQueryItem, render::view::ViewTarget};
 use bevy::ecs::system::lifetimeless::{Read, SRes};
 use bevy::ecs::system::{SystemParamItem, SystemState};
 use bevy::prelude::*;
@@ -202,6 +202,7 @@ bitflags::bitflags! {
         const DEPTH              = (1 << 1);
         const LOCK_Y             = (1 << 2);
         const LOCK_ROTATION      = (1 << 3);
+        const HDR                = (1 << 4);
         const MSAA_RESERVED_BITS = Self::MSAA_MASK_BITS << Self::MSAA_SHIFT_BITS;
     }
 }
@@ -323,7 +324,7 @@ impl SpecializedMeshPipeline for BillboardPipeline {
                 entry_point: "fragment".into(),
                 shader_defs,
                 targets: vec![Some(ColorTargetState {
-                    format: TextureFormat::bevy_default(),
+                    format: if key.contains(BillboardPipelineKey::HDR) { ViewTarget::TEXTURE_FORMAT_HDR } else { TextureFormat::bevy_default() },
                     blend: Some(BlendState {
                         color: BlendComponent {
                             src_factor: BlendFactor::SrcAlpha,
@@ -682,6 +683,10 @@ pub fn queue_billboard_texture(
                 key |= BillboardPipelineKey::LOCK_ROTATION;
             }

+            if view.hdr {
+                key |= BillboardPipelineKey::HDR;
+            }
+
             let (array_handle, array_image, pipeline_id, texture_layout) = match billboard_type {
                 BillboardTextureType::Single(array_handle, array_image) => (
                     array_handle,
```

**Comment by kulkalkul** [comment]
@robtfm Let's add it to this one as it is 0.11 feature 😅

**Comment by kulkalkul** [comment]
I'd like to ask about https://github.com/kulkalkul/bevy_mod_billboard/pull/13/commits/d9ceeba893b8ebe856a83756221a298e323cc7fd. While creating the lock_rotation example, I noticed text looks inverted So I updated the shader to solve it, though I'm not sure if this is something to be solved. What do you think of it?

**Comment by robtfm** [comment]
yes that looks better. i'm not sure where the inversion comes from (the shader code was from the standard vertex shader), but it is definitely more sensible to have the look-at be the direction the text faces

**Pull request merged**
