### PR TITLE
bevy 12

### PR DESCRIPTION
**Pull request by robtfm**
a mechanical port to bevy 0.12 - just enough to get it to work.

in particular i haven't considered batching at all.

### CODE REVIEW

**Comment by dividebysandwich** [comment]
Could we get this merged in please? Thanks a lot!

**Comment by kulkalkul** [comment]
> Could we get this merged in please? Thanks a lot!

I have another branch where I was working on rewriting this so it would be easy to batch it. Current implementation I have has issues with lots of text and quickly changing texts. I was thinking of finishing that first and then upgrading to 0.12. In bevy discord, we talked about upstreaming this into bevy 0.13. Here is the related Discord thread if you are interested in:

https://discord.com/channels/691052431525675048/1170975253967671418

So, that update will be breaking, so I didn't want to release two breaking changes (one for version, one for rewrite) for 0.12. So if it is okay, it would be best to use robftm's repo temporarily. Right now I'm struggling with lots of projects but as soon as I can find some free time I'll finish my work, commit it, merge it and release it so upstreaming process can start next month. 😅

Here is how you can do it if you are unfamiliar with cargo:
```toml
bevy_mod_billboard = { git = "https://github.com/robtfm/bevy_mod_billboard/", branch = "bevy12" }
```

**Comment by dividebysandwich** [comment]
Aye, that makes a lot of sense. And +1 on the upstreaming, this is such a sensible feature to have in core. Much appreciated!!

**Comment by kulkalkul** [comment]
There were lots of merge conflicts with the new implementation as I don't use cargo fmt (I'll do it now). Just reimplemented this with some changes in #18. Thanks!

**Pull request closed without merging**
