### PR TITLE
Upgrade bevy to 0.14

### PR DESCRIPTION
**Pull request by interwhy**
Hey, I upgraded bevy to the new version although we might want to wait until 0.14 is officially released to merge it in. These were the main changes (but I might've missed one or two):

- https://github.com/bevyengine/bevy/pull/12067 New color palette
- https://github.com/bevyengine/bevy/pull/12827 `RenderAssets<Image>` is now `RenderAssets<GpuImage>` 
- https://github.com/bevyengine/bevy/pull/13277 `RenderPhase`s are now stored in a resource `ViewSortedRenderPhases`
- https://github.com/bevyengine/bevy/pull/12216 `MeshVertexBufferLayout` is now `MeshVertexBufferLayoutRef`
- https://github.com/bevyengine/bevy/pull/11698 Image dimensions are now in `UVec2`s
- https://github.com/bevyengine/bevy/pull/12582 We have to explicitly add custom text/mesh handle components to the `CheckVisibility` schedule

Thanks!

### CODE REVIEW

**Comment by kulkalkul** [comment]
Thanks a lot! I'll read it after 0.14 is released and then we can merge 🥳

**Comment by marcelchampagne** [comment]
@kulkalkul and @interwhy FYI if you haven't been following along on the Bevy Discord that 0.14 has been officially released. Would be great to see this be updated to upgrade to 0.14 and merged. Let me know if either of you would like help doing that.

**Comment by kulkalkul** [comment]
Thanks for the update, I'll look into it during weekend 😅

2 days later: I'll take a look into this tomorrow

**Comment by kulkalkul** [comment]
Seems like there are changes from 0.14rc2 -> 0.14. I'll be reading update post to figure what those are.

**Comment by kulkalkul** [comment]
Thanks a lot! I'll be releasing this in several minutes, after some meta changes like CHANGELOG and README.

**Pull request merged**
