### PR TITLE
Debug and fix memory leak

### LINKED ISSUE #4: Memory leak
When working on https://github.com/Leafwing-Studios/Emergence/pull/613, I encountered a memory leak, which ultimately led to a panic due to my GPU running out of memory.

This was the commit in question: https://github.com/Leafwing-Studios/Emergence/pull/613/commits/0f60c50a763f7d511e250f59a323ececaad6381d

Here's what my system monitor looked like, before and after toggling on the billboarded text via the F2 key.

image

The drop is when the game crashed 😅 

I'm using this in a simple immediate mode way for now, as seen [here](https://github.com/Leafwing-Studios/Emergence/pull/613/files#diff-1d82eb57924c3cc05bc4a14ed7b054a481f9ab3fb3dc9e8fa90d4dc702ffdf06R49), but I *am* being careful to reuse assets and despawn my entities each frame.

### PR DESCRIPTION
**Pull request by alice-i-cecile**
Draft PR, but I'm hoping to fix #4.

To do:

- [x] create a minimal reproducible example, and verify that memory usage balloons
- [ ] investigate the size of each of the types used in this crate, and see which ones are growing
- [ ] fix the bug(s)

### CODE REVIEW

**Comment by kulkalkul** [comment]
I made two changes:

- Crate uses its own ImageBindGroups struct (because values is not pub), so changed the import on the example.

- size_of_val looks like can't measure heap memory usage, instead of that made ``values`` temporarily pub and checked via .values.len().

With these changes, I can see that size of ImageBindGroups unbounded, keeps increasing, causing memory leak. 😦

**Comment by kulkalkul** [comment]
I did hijack your PR, hope you are okay with it 😁. I made a mistake assuming clone_weaks would remove theirselves from hashmap as if rust is a GC language (I don't think GC handles this either tbh) 😅.

So, borrowing from [bevy_sprite](https://github.com/bevyengine/bevy/blob/release-0.10.1/crates/bevy_sprite/src/render/mod.rs#L502) and [bevy_ui](https://github.com/bevyengine/bevy/blob/release-0.10.1/crates/bevy_ui/src/render/mod.rs#L578), I've added this. With this, I can't reproduce it with the example anymore, so I hope it is solved.
```rs
for event in &events.images {
    match event {
        AssetEvent::Created { .. } => None,
        AssetEvent::Modified { handle } | AssetEvent::Removed { handle } => {
            image_bind_groups.values.remove(handle)
        }
    };
}
```
It is created at:
https://github.com/bevyengine/bevy/blob/release-0.10.1/crates/bevy_sprite/src/render/mod.rs#L330

I have two possible issues though, that I'd like to get your thoughts:

- This would couple the library to bevy_sprite. So, SpritePlugin would have to be enabled in that case. I don't know how much of an issue this really is. Alternative is replicating what extract_sprite_events does, though that would have overhead compared to this. Maybe adding a feature could work, but I don't know if this is an issue worth the complexity.

- Even though it is negligible, iterating over all image change events feels wrong. Though it seems like I'll have to accept it for now 😅.

I'll also change name of ImageBindGroups to BillboardImageBindGroups for clarity, but including it into this PR felt wrong, so left it to later.

**Comment by alice-i-cecile** [comment]
> size_of_val looks like can't measure heap memory usage, instead of that made values temporarily pub and checked via .values.len().

Aha, I was wondering why the results were looking suspicious. Thanks!

> I did hijack your PR, hope you are okay with it

Yep, very happy to collaborate on this and get it fixed. Thanks for the prompt and expert response!

The fix makes a ton of sense; let me try and replicate it.

> This would couple the library to bevy_sprite. So, SpritePlugin would have to be enabled in that case. I don't know how much of an issue this really is.

I think this is reasonable: as the billboarding / Bevy's ordinary 2D features grow and evolve I would expect them to share more code over time.

> Even though it is negligible, iterating over all image change events feels wrong. Though it seems like I'll have to accept it for now sweat_smile.

Yeah, I think just tracking what's being done upstream is the way to go for now :)

**Comment by alice-i-cecile** [comment]
Alright @kulkalkul I've verified that this works, and I've cleaned up the now useless example and the TODO you left :)

This is ready for review now; feel free to make whatever changes you see fit.

I think it's correct to make the modules pub still (since there are pub types in there that were otherwise inaccessible), but I'm fine to cut that if you feel otherwise (or just want a cleaner PR) :)

**Comment by kulkalkul** [comment]
@alice-i-cecile Thanks! I was trying to hide complexity with that. I don't know much about crate hygiene, so I'd like to ask to you. Stuff like BillboardViewBindGroup, BillboardUniform etc. will all be accessible in that case. I don't know if that's something preferred or not, so is it?

**Comment by alice-i-cecile** [comment]
So, my feeling is that public types should be genuinely accessible, unless you have a good reason to not do so (like the sealed trait pattern).

In this case, it looks like these types need to be public to enable their system to be public (which is a good goal). Keeping these types public will be less surprising, increase the amount of flexibility in the crate before it needs to be forked, and enable external debugging.

I think that examples do a better job of complexity management here: 99% of users will go to those, copy-paste so it works and move on with their project :)

**Comment by kulkalkul** [comment]
Thanks for thorough explanation!

**Pull request merged**
